// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;


#region ISI.Extensions.PfSense.T4Embedded
namespace ISI.Extensions.PfSense
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Embedded
	{
		public static string _root()
		{
			return "pack://application:,,,/ISI.Extensions.PfSense;component/";
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Content
		{
			public static string _root()
			{
				return string.Format("{0}Content/", T4Embedded._root());
			}
		
			public static readonly string pfsense_import_certificate_php = _root() + "pfsense-import-certificate.php";
			public static System.IO.Stream Getpfsense_import_certificate_phpStream()
			{
				return typeof(ISI.Extensions.PfSense.T4Resources).Assembly.GetManifestResourceStream(pfsense_import_certificate_php);
			}
		}
	}
}
#endregion

#region ISI.Extensions.PfSense.T4Resources
namespace ISI.Extensions.PfSense
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Resources
	{
		public static string _root()
		{
			return "ISI.Extensions.PfSense.";
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Content
		{
			public static string _root()
			{
				return string.Format("{0}Content.", T4Resources._root());
			}
		
			public static readonly string pfsense_import_certificate_php = _root() + "pfsense-import-certificate.php";
			public static System.IO.Stream Getpfsense_import_certificate_phpStream()
			{
				return typeof(ISI.Extensions.PfSense.T4Resources).Assembly.GetManifestResourceStream(pfsense_import_certificate_php);
			}
		}
	}
}
#endregion


