// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

#region ISI.Extensions.Cake.T4Files
namespace ISI.Extensions.Cake
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Files
	{
		public static string __root = null;
		public static string _root()
		{
			return (__root ??= ISI.Extensions.VirtualFileVolumesFileProvider.GetPathPrefix(typeof(T4Files)));
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Artwork
		{
			public static string _root()
			{
				return string.Format("{0}Artwork/", T4Files._root());
			}
		
			public static readonly string Cake_ico = _root() + "Cake.ico";
			public static System.IO.Stream GetCake_icoStream()
			{
				return typeof(ISI.Extensions.Cake.T4Resources).Assembly.GetManifestResourceStream(Cake_ico);
			}
			public static readonly string Cake_16x16_png = _root() + "Cake-16x16.png";
			public static System.IO.Stream GetCake_16x16_pngStream()
			{
				return typeof(ISI.Extensions.Cake.T4Resources).Assembly.GetManifestResourceStream(Cake_16x16_png);
			}
		}
	}
}
#endregion


#region ISI.Extensions.Cake.T4Embedded
namespace ISI.Extensions.Cake
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Embedded
	{
		public static string _root()
		{
			return "pack://application:,,,/ISI.Extensions.Cake;component/";
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Artwork
		{
			public static string _root()
			{
				return string.Format("{0}Artwork/", T4Embedded._root());
			}
		
			public static readonly string Cake_ico = _root() + "Cake.ico";
			public static System.IO.Stream GetCake_icoStream()
			{
				return typeof(ISI.Extensions.Cake.T4Resources).Assembly.GetManifestResourceStream(Cake_ico);
			}
			public static readonly string Cake_16x16_png = _root() + "Cake-16x16.png";
			public static System.IO.Stream GetCake_16x16_pngStream()
			{
				return typeof(ISI.Extensions.Cake.T4Resources).Assembly.GetManifestResourceStream(Cake_16x16_png);
			}
		}
	}
}
#endregion

#region ISI.Extensions.Cake.T4Resources
namespace ISI.Extensions.Cake
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Resources
	{
		public static string _root()
		{
			return "ISI.Extensions.Cake.";
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Artwork
		{
			public static string _root()
			{
				return string.Format("{0}Artwork.", T4Resources._root());
			}
		
			public static readonly string Cake_ico = _root() + "Cake.ico";
			public static System.IO.Stream GetCake_icoStream()
			{
				return typeof(ISI.Extensions.Cake.T4Resources).Assembly.GetManifestResourceStream(Cake_ico);
			}
			public static readonly string Cake_16x16_png = _root() + "Cake-16x16.png";
			public static System.IO.Stream GetCake_16x16_pngStream()
			{
				return typeof(ISI.Extensions.Cake.T4Resources).Assembly.GetManifestResourceStream(Cake_16x16_png);
			}
		}
	}
}
#endregion


