//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://services-manager.isi-net.com/manager/data-transfer-objects", ClrNamespace = "ISI.Extensions.Scm.ServiceReferences.ServicesManager")]

namespace ISI.Extensions.Scm.ServiceReferences.ServicesManager
{
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.CollectionDataContractAttribute(Name = "DeployComponentCollection", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects", ItemName = "anyType")]
	public class DeployComponentCollection : System.Collections.Generic.List<object>
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployConsoleApplication", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class DeployConsoleApplication : object
	{
		private string ConsoleApplicationExeField;

		private string DeployToSubfolderField;

		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFilesField;

		private bool ExecuteConsoleApplicationAfterInstallField;

		private string ExecuteConsoleApplicationAfterInstallArgumentsField;

		private string PackageFolderField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string ConsoleApplicationExe
		{
			get { return this.ConsoleApplicationExeField; }
			set { this.ConsoleApplicationExeField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get { return this.DeployToSubfolderField; }
			set { this.DeployToSubfolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFiles
		{
			get { return this.ExcludeFilesField; }
			set { this.ExcludeFilesField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool ExecuteConsoleApplicationAfterInstall
		{
			get { return this.ExecuteConsoleApplicationAfterInstallField; }
			set { this.ExecuteConsoleApplicationAfterInstallField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string ExecuteConsoleApplicationAfterInstallArguments
		{
			get { return this.ExecuteConsoleApplicationAfterInstallArgumentsField; }
			set { this.ExecuteConsoleApplicationAfterInstallArgumentsField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get { return this.PackageFolderField; }
			set { this.PackageFolderField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.CollectionDataContractAttribute(Name = "DeployComponentExcludeFileCollection", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects", ItemName = "DeployComponentExcludeFile")]
	public class DeployComponentExcludeFileCollection : System.Collections.Generic.List<ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFile>
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployComponentExcludeFile", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class DeployComponentExcludeFile : object
	{
		private string ExcludeFileField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string ExcludeFile
		{
			get { return this.ExcludeFileField; }
			set { this.ExcludeFileField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployWebSite", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class DeployWebSite : object
	{

		private string DeployToSubfolderField;

		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFilesField;

		private string PackageFolderField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get { return this.DeployToSubfolderField; }
			set { this.DeployToSubfolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFiles
		{
			get { return this.ExcludeFilesField; }
			set { this.ExcludeFilesField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get { return this.PackageFolderField; }
			set { this.PackageFolderField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployWindowsService", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class DeployWindowsService : object
	{

		private string DeployToSubfolderField;

		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFilesField;

		private string PackageFolderField;

		private bool UninstallIfInstalledField;

		private string WindowsServiceExeField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get { return this.DeployToSubfolderField; }
			set { this.DeployToSubfolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFiles
		{
			get { return this.ExcludeFilesField; }
			set { this.ExcludeFilesField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get { return this.PackageFolderField; }
			set { this.PackageFolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool UninstallIfInstalled
		{
			get { return this.UninstallIfInstalledField; }
			set { this.UninstallIfInstalledField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string WindowsServiceExe
		{
			get { return this.WindowsServiceExeField; }
			set { this.WindowsServiceExeField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployConsoleApplicationResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class DeployConsoleApplicationResponse : object
	{

		private string ConsoleApplicationExeField;

		private string DeployToSubfolderField;

		private bool InstalledField;

		private string LogField;

		private bool NewInstallField;

		private string PackageFolderField;

		private bool SameVersionField;

		private bool SuccessField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string ConsoleApplicationExe
		{
			get { return this.ConsoleApplicationExeField; }
			set { this.ConsoleApplicationExeField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get { return this.DeployToSubfolderField; }
			set { this.DeployToSubfolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Installed
		{
			get { return this.InstalledField; }
			set { this.InstalledField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Log
		{
			get { return this.LogField; }
			set { this.LogField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool NewInstall
		{
			get { return this.NewInstallField; }
			set { this.NewInstallField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get { return this.PackageFolderField; }
			set { this.PackageFolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool SameVersion
		{
			get { return this.SameVersionField; }
			set { this.SameVersionField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Success
		{
			get { return this.SuccessField; }
			set { this.SuccessField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployWebSiteResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class DeployWebSiteResponse : object
	{
		private string DeployToSubfolderField;

		private bool InstalledField;

		private string LogField;

		private bool NewInstallField;

		private string PackageFolderField;

		private bool SameVersionField;

		private bool SuccessField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get { return this.DeployToSubfolderField; }
			set { this.DeployToSubfolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Installed
		{
			get { return this.InstalledField; }
			set { this.InstalledField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Log
		{
			get { return this.LogField; }
			set { this.LogField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool NewInstall
		{
			get { return this.NewInstallField; }
			set { this.NewInstallField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get { return this.PackageFolderField; }
			set { this.PackageFolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool SameVersion
		{
			get { return this.SameVersionField; }
			set { this.SameVersionField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Success
		{
			get { return this.SuccessField; }
			set { this.SuccessField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployWindowsServiceResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class DeployWindowsServiceResponse : object
	{

		private bool CurrentVersionStoppedField;

		private string DeployToSubfolderField;

		private bool InstalledField;

		private string LogField;

		private bool NewInstallField;

		private bool NewVersionStartedField;

		private string PackageFolderField;

		private bool SameVersionField;

		private bool SuccessField;

		private bool UninstalledField;

		private string WindowsServiceExeField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool CurrentVersionStopped
		{
			get { return this.CurrentVersionStoppedField; }
			set { this.CurrentVersionStoppedField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get { return this.DeployToSubfolderField; }
			set { this.DeployToSubfolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Installed
		{
			get { return this.InstalledField; }
			set { this.InstalledField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Log
		{
			get { return this.LogField; }
			set { this.LogField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool NewInstall
		{
			get { return this.NewInstallField; }
			set { this.NewInstallField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool NewVersionStarted
		{
			get { return this.NewVersionStartedField; }
			set { this.NewVersionStartedField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get { return this.PackageFolderField; }
			set { this.PackageFolderField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool SameVersion
		{
			get { return this.SameVersionField; }
			set { this.SameVersionField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Success
		{
			get { return this.SuccessField; }
			set { this.SuccessField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Uninstalled
		{
			get { return this.UninstalledField; }
			set { this.UninstalledField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string WindowsServiceExe
		{
			get { return this.WindowsServiceExeField; }
			set { this.WindowsServiceExeField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "GetStatusResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class GetStatusResponse : ISI.Extensions.Scm.ServiceReferences.ServicesManager.Response
	{

		private bool ActiveField;

		private string CaptionField;

		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntryCollection LogField;

		private int PercentField;

		private bool SuccessField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Active
		{
			get { return this.ActiveField; }
			set { this.ActiveField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Caption
		{
			get { return this.CaptionField; }
			set { this.CaptionField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntryCollection Log
		{
			get { return this.LogField; }
			set { this.LogField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public int Percent
		{
			get { return this.PercentField; }
			set { this.PercentField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Success
		{
			get { return this.SuccessField; }
			set { this.SuccessField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "UpdateResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class UpdateResponse : ISI.Extensions.Scm.ServiceReferences.ServicesManager.Response
	{

		private string CurrentVersionField;

		private string LogField;

		private string NewVersionField;

		private bool SameVersionField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string CurrentVersion
		{
			get { return this.CurrentVersionField; }
			set { this.CurrentVersionField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Log
		{
			get { return this.LogField; }
			set { this.LogField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string NewVersion
		{
			get { return this.NewVersionField; }
			set { this.NewVersionField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool SameVersion
		{
			get { return this.SameVersionField; }
			set { this.SameVersionField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployArtifactResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployConsoleApplication))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFile))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWebSite))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWindowsService))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployConsoleApplicationResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWebSiteResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWindowsServiceResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentCollection))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentResponseCollection))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntryCollection))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntry))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.Response))]
	public partial class DeployArtifactResponse : ISI.Extensions.Scm.ServiceReferences.ServicesManager.Response
	{
		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentResponseCollection DeployComponentResponsesField;

		private string StatusTrackerKeyField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentResponseCollection DeployComponentResponses
		{
			get { return this.DeployComponentResponsesField; }
			set { this.DeployComponentResponsesField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string StatusTrackerKey
		{
			get { return this.StatusTrackerKeyField; }
			set { this.StatusTrackerKeyField = value; }
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.CollectionDataContractAttribute(Name = "DeployComponentResponseCollection", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects", ItemName = "anyType")]
	public class DeployComponentResponseCollection : System.Collections.Generic.List<object>
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.CollectionDataContractAttribute(Name = "LogEntryCollection", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects", ItemName = "LogEntry")]
	public class LogEntryCollection : System.Collections.Generic.List<ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntry>
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "LogEntry", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	public partial class LogEntry : object
	{
		private System.DateTime DateTimeStampField;

		private string DescriptionField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public System.DateTime DateTimeStamp
		{
			get { return this.DateTimeStampField; }
			set { this.DateTimeStampField = value; }
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Description
		{
			get { return this.DescriptionField; }
			set { this.DescriptionField = value; }
		}
	}


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "response", Namespace = "http://schemas.datacontract.org/2004/07/ISI.Extensions.Scm.ServiceReferences.ServicesManager")]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployArtifactResponse))]
	public partial class Response : object
	{
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://services-manager.isi-net.com", ConfigurationName = "Manager")]
	public interface IManager
	{
		[System.ServiceModel.OperationContractAttribute(Action = "http://services-manager.isi-net.com/Manager/DeployArtifact", ReplyAction = "http://services-manager.isi-net.com/Manager/DeployArtifactResponse")]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployConsoleApplication))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFile))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWebSite))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWindowsService))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployConsoleApplicationResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWebSiteResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWindowsServiceResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentCollection))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployArtifactResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentResponseCollection))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntryCollection))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntry))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.Response))]
		System.Threading.Tasks.Task<ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployArtifactResponse> DeployArtifactAsync(string password, string remoteManagementUrl, string authenticationToken, string artifactName, string artifactDateTimeStampVersionUrl, string artifactDownloadUrl, string toDateTimeStamp, string fromEnvironment, string toEnvironment, string configurationKey, ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentCollection deployComponents, bool setDeployedVersion, bool runAsync);

		[System.ServiceModel.OperationContractAttribute(Action = "http://services-manager.isi-net.com/Manager/GetStatus", ReplyAction = "http://services-manager.isi-net.com/Manager/GetStatusResponse")]
		System.Threading.Tasks.Task<ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse> GetStatusAsync(string password, string statusTrackerKey);

		[System.ServiceModel.OperationContractAttribute(Action = "http://services-manager.isi-net.com/Manager/Update", ReplyAction = "http://services-manager.isi-net.com/Manager/UpdateResponse")]
		System.Threading.Tasks.Task<ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse> UpdateAsync(string password);
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	public interface IManagerChannel : IManager, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
	public partial class ManagerClient : System.ServiceModel.ClientBase<IManager>, IManager
	{
		/// <summary>
		/// Implement this partial method to configure the service endpoint.
		/// </summary>
		/// <param name="serviceEndpoint">The endpoint to configure</param>
		/// <param name="clientCredentials">The client credentials</param>
		static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

		public ManagerClient() :
			base(ManagerClient.GetDefaultBinding(), ManagerClient.GetDefaultEndpointAddress())
		{
			this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_Manager.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public ManagerClient(EndpointConfiguration endpointConfiguration) :
			base(ManagerClient.GetBindingForEndpoint(endpointConfiguration), ManagerClient.GetEndpointAddress(endpointConfiguration))
		{
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public ManagerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
			base(ManagerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
		{
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public ManagerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
			base(ManagerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
		{
			this.Endpoint.Name = endpointConfiguration.ToString();
			ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
		}

		public ManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
			base(binding, remoteAddress)
		{
		}

		public System.Threading.Tasks.Task<ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployArtifactResponse> DeployArtifactAsync(string password, string remoteManagementUrl, string authenticationToken, string artifactName, string artifactDateTimeStampVersionUrl, string artifactDownloadUrl, string toDateTimeStamp, string fromEnvironment, string toEnvironment, string configurationKey, ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentCollection deployComponents, bool setDeployedVersion, bool runAsync)
		{
			return base.Channel.DeployArtifactAsync(password, remoteManagementUrl, authenticationToken, artifactName, artifactDateTimeStampVersionUrl, artifactDownloadUrl, toDateTimeStamp, fromEnvironment, toEnvironment, configurationKey, deployComponents, setDeployedVersion, runAsync);
		}

		public System.Threading.Tasks.Task<ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse> GetStatusAsync(string password, string statusTrackerKey)
		{
			return base.Channel.GetStatusAsync(password, statusTrackerKey);
		}

		public System.Threading.Tasks.Task<ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse> UpdateAsync(string password)
		{
			return base.Channel.UpdateAsync(password);
		}

		public virtual System.Threading.Tasks.Task OpenAsync()
		{
			return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
		}

		public virtual System.Threading.Tasks.Task CloseAsync()
		{
			return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
		}

		private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
		{
			if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_Manager))
			{
				System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
				System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
				result.Elements.Add(textBindingElement);
				System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
				httpsBindingElement.AllowCookies = true;
				httpsBindingElement.MaxBufferSize = int.MaxValue;
				httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
				result.Elements.Add(httpsBindingElement);
				return result;
			}

			throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
		}

		private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
		{
			if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_Manager))
			{
				return new System.ServiceModel.EndpointAddress("https://isinyscm01-servicesmanager.isi-net.com:37443/manager/");
			}

			throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
		}

		private static System.ServiceModel.Channels.Binding GetDefaultBinding()
		{
			return ManagerClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_Manager);
		}

		private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
		{
			return ManagerClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_Manager);
		}

		public enum EndpointConfiguration
		{

			WSHttpBinding_Manager,
		}
	}
}
