//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISI.Extensions.Scm.ServiceReferences.ServicesManager
{
	using System.Runtime.Serialization;
	using System;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.CollectionDataContractAttribute(Name = "DeployComponentCollection", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects", ItemName = "anyType")]
	[System.SerializableAttribute()]
	public class DeployComponentCollection : System.Collections.Generic.List<object>
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployConsoleApplication", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class DeployConsoleApplication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string ConsoleApplicationExeField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string DeployToSubfolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFilesField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool ExecuteConsoleApplicationAfterInstallField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string ExecuteConsoleApplicationAfterInstallArgumentsField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string PackageFolderField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string ConsoleApplicationExe
		{
			get
			{
				return this.ConsoleApplicationExeField;
			}
			set
			{
				if ((object.ReferenceEquals(this.ConsoleApplicationExeField, value) != true))
				{
					this.ConsoleApplicationExeField = value;
					this.RaisePropertyChanged("ConsoleApplicationExe");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get
			{
				return this.DeployToSubfolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.DeployToSubfolderField, value) != true))
				{
					this.DeployToSubfolderField = value;
					this.RaisePropertyChanged("DeployToSubfolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFiles
		{
			get
			{
				return this.ExcludeFilesField;
			}
			set
			{
				if ((object.ReferenceEquals(this.ExcludeFilesField, value) != true))
				{
					this.ExcludeFilesField = value;
					this.RaisePropertyChanged("ExcludeFiles");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool ExecuteConsoleApplicationAfterInstall
		{
			get
			{
				return this.ExecuteConsoleApplicationAfterInstallField;
			}
			set
			{
				if ((this.ExecuteConsoleApplicationAfterInstallField.Equals(value) != true))
				{
					this.ExecuteConsoleApplicationAfterInstallField = value;
					this.RaisePropertyChanged("ExecuteConsoleApplicationAfterInstall");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string ExecuteConsoleApplicationAfterInstallArguments
		{
			get
			{
				return this.ExecuteConsoleApplicationAfterInstallArgumentsField;
			}
			set
			{
				if ((object.ReferenceEquals(this.ExecuteConsoleApplicationAfterInstallArgumentsField, value) != true))
				{
					this.ExecuteConsoleApplicationAfterInstallArgumentsField = value;
					this.RaisePropertyChanged("ExecuteConsoleApplicationAfterInstallArguments");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get
			{
				return this.PackageFolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.PackageFolderField, value) != true))
				{
					this.PackageFolderField = value;
					this.RaisePropertyChanged("PackageFolder");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.CollectionDataContractAttribute(Name = "DeployComponentExcludeFileCollection", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects", ItemName = "DeployComponentExcludeFile")]
	[System.SerializableAttribute()]
	public class DeployComponentExcludeFileCollection : System.Collections.Generic.List<ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFile>
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployComponentExcludeFile", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class DeployComponentExcludeFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string ExcludeFileField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string ExcludeFile
		{
			get
			{
				return this.ExcludeFileField;
			}
			set
			{
				if ((object.ReferenceEquals(this.ExcludeFileField, value) != true))
				{
					this.ExcludeFileField = value;
					this.RaisePropertyChanged("ExcludeFile");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployWebSite", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class DeployWebSite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string DeployToSubfolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFilesField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string PackageFolderField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get
			{
				return this.DeployToSubfolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.DeployToSubfolderField, value) != true))
				{
					this.DeployToSubfolderField = value;
					this.RaisePropertyChanged("DeployToSubfolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFiles
		{
			get
			{
				return this.ExcludeFilesField;
			}
			set
			{
				if ((object.ReferenceEquals(this.ExcludeFilesField, value) != true))
				{
					this.ExcludeFilesField = value;
					this.RaisePropertyChanged("ExcludeFiles");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get
			{
				return this.PackageFolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.PackageFolderField, value) != true))
				{
					this.PackageFolderField = value;
					this.RaisePropertyChanged("PackageFolder");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployWindowsService", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class DeployWindowsService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string DeployToSubfolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFilesField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string PackageFolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool UninstallIfInstalledField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string WindowsServiceExeField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get
			{
				return this.DeployToSubfolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.DeployToSubfolderField, value) != true))
				{
					this.DeployToSubfolderField = value;
					this.RaisePropertyChanged("DeployToSubfolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection ExcludeFiles
		{
			get
			{
				return this.ExcludeFilesField;
			}
			set
			{
				if ((object.ReferenceEquals(this.ExcludeFilesField, value) != true))
				{
					this.ExcludeFilesField = value;
					this.RaisePropertyChanged("ExcludeFiles");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get
			{
				return this.PackageFolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.PackageFolderField, value) != true))
				{
					this.PackageFolderField = value;
					this.RaisePropertyChanged("PackageFolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool UninstallIfInstalled
		{
			get
			{
				return this.UninstallIfInstalledField;
			}
			set
			{
				if ((this.UninstallIfInstalledField.Equals(value) != true))
				{
					this.UninstallIfInstalledField = value;
					this.RaisePropertyChanged("UninstallIfInstalled");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string WindowsServiceExe
		{
			get
			{
				return this.WindowsServiceExeField;
			}
			set
			{
				if ((object.ReferenceEquals(this.WindowsServiceExeField, value) != true))
				{
					this.WindowsServiceExeField = value;
					this.RaisePropertyChanged("WindowsServiceExe");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployConsoleApplicationResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class DeployConsoleApplicationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string ConsoleApplicationExeField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string DeployToSubfolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool InstalledField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string LogField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool NewInstallField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string PackageFolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool SameVersionField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool SuccessField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string ConsoleApplicationExe
		{
			get
			{
				return this.ConsoleApplicationExeField;
			}
			set
			{
				if ((object.ReferenceEquals(this.ConsoleApplicationExeField, value) != true))
				{
					this.ConsoleApplicationExeField = value;
					this.RaisePropertyChanged("ConsoleApplicationExe");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get
			{
				return this.DeployToSubfolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.DeployToSubfolderField, value) != true))
				{
					this.DeployToSubfolderField = value;
					this.RaisePropertyChanged("DeployToSubfolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Installed
		{
			get
			{
				return this.InstalledField;
			}
			set
			{
				if ((this.InstalledField.Equals(value) != true))
				{
					this.InstalledField = value;
					this.RaisePropertyChanged("Installed");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Log
		{
			get
			{
				return this.LogField;
			}
			set
			{
				if ((object.ReferenceEquals(this.LogField, value) != true))
				{
					this.LogField = value;
					this.RaisePropertyChanged("Log");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool NewInstall
		{
			get
			{
				return this.NewInstallField;
			}
			set
			{
				if ((this.NewInstallField.Equals(value) != true))
				{
					this.NewInstallField = value;
					this.RaisePropertyChanged("NewInstall");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get
			{
				return this.PackageFolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.PackageFolderField, value) != true))
				{
					this.PackageFolderField = value;
					this.RaisePropertyChanged("PackageFolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool SameVersion
		{
			get
			{
				return this.SameVersionField;
			}
			set
			{
				if ((this.SameVersionField.Equals(value) != true))
				{
					this.SameVersionField = value;
					this.RaisePropertyChanged("SameVersion");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Success
		{
			get
			{
				return this.SuccessField;
			}
			set
			{
				if ((this.SuccessField.Equals(value) != true))
				{
					this.SuccessField = value;
					this.RaisePropertyChanged("Success");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployWebSiteResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class DeployWebSiteResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string DeployToSubfolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool InstalledField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string LogField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool NewInstallField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string PackageFolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool SameVersionField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool SuccessField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get
			{
				return this.DeployToSubfolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.DeployToSubfolderField, value) != true))
				{
					this.DeployToSubfolderField = value;
					this.RaisePropertyChanged("DeployToSubfolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Installed
		{
			get
			{
				return this.InstalledField;
			}
			set
			{
				if ((this.InstalledField.Equals(value) != true))
				{
					this.InstalledField = value;
					this.RaisePropertyChanged("Installed");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Log
		{
			get
			{
				return this.LogField;
			}
			set
			{
				if ((object.ReferenceEquals(this.LogField, value) != true))
				{
					this.LogField = value;
					this.RaisePropertyChanged("Log");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool NewInstall
		{
			get
			{
				return this.NewInstallField;
			}
			set
			{
				if ((this.NewInstallField.Equals(value) != true))
				{
					this.NewInstallField = value;
					this.RaisePropertyChanged("NewInstall");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get
			{
				return this.PackageFolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.PackageFolderField, value) != true))
				{
					this.PackageFolderField = value;
					this.RaisePropertyChanged("PackageFolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool SameVersion
		{
			get
			{
				return this.SameVersionField;
			}
			set
			{
				if ((this.SameVersionField.Equals(value) != true))
				{
					this.SameVersionField = value;
					this.RaisePropertyChanged("SameVersion");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Success
		{
			get
			{
				return this.SuccessField;
			}
			set
			{
				if ((this.SuccessField.Equals(value) != true))
				{
					this.SuccessField = value;
					this.RaisePropertyChanged("Success");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployWindowsServiceResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class DeployWindowsServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool CurrentVersionStoppedField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string DeployToSubfolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool InstalledField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string LogField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool NewInstallField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool NewVersionStartedField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string PackageFolderField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool SameVersionField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool SuccessField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool UninstalledField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string WindowsServiceExeField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool CurrentVersionStopped
		{
			get
			{
				return this.CurrentVersionStoppedField;
			}
			set
			{
				if ((this.CurrentVersionStoppedField.Equals(value) != true))
				{
					this.CurrentVersionStoppedField = value;
					this.RaisePropertyChanged("CurrentVersionStopped");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string DeployToSubfolder
		{
			get
			{
				return this.DeployToSubfolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.DeployToSubfolderField, value) != true))
				{
					this.DeployToSubfolderField = value;
					this.RaisePropertyChanged("DeployToSubfolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Installed
		{
			get
			{
				return this.InstalledField;
			}
			set
			{
				if ((this.InstalledField.Equals(value) != true))
				{
					this.InstalledField = value;
					this.RaisePropertyChanged("Installed");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Log
		{
			get
			{
				return this.LogField;
			}
			set
			{
				if ((object.ReferenceEquals(this.LogField, value) != true))
				{
					this.LogField = value;
					this.RaisePropertyChanged("Log");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool NewInstall
		{
			get
			{
				return this.NewInstallField;
			}
			set
			{
				if ((this.NewInstallField.Equals(value) != true))
				{
					this.NewInstallField = value;
					this.RaisePropertyChanged("NewInstall");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool NewVersionStarted
		{
			get
			{
				return this.NewVersionStartedField;
			}
			set
			{
				if ((this.NewVersionStartedField.Equals(value) != true))
				{
					this.NewVersionStartedField = value;
					this.RaisePropertyChanged("NewVersionStarted");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string PackageFolder
		{
			get
			{
				return this.PackageFolderField;
			}
			set
			{
				if ((object.ReferenceEquals(this.PackageFolderField, value) != true))
				{
					this.PackageFolderField = value;
					this.RaisePropertyChanged("PackageFolder");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool SameVersion
		{
			get
			{
				return this.SameVersionField;
			}
			set
			{
				if ((this.SameVersionField.Equals(value) != true))
				{
					this.SameVersionField = value;
					this.RaisePropertyChanged("SameVersion");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Success
		{
			get
			{
				return this.SuccessField;
			}
			set
			{
				if ((this.SuccessField.Equals(value) != true))
				{
					this.SuccessField = value;
					this.RaisePropertyChanged("Success");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Uninstalled
		{
			get
			{
				return this.UninstalledField;
			}
			set
			{
				if ((this.UninstalledField.Equals(value) != true))
				{
					this.UninstalledField = value;
					this.RaisePropertyChanged("Uninstalled");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string WindowsServiceExe
		{
			get
			{
				return this.WindowsServiceExeField;
			}
			set
			{
				if ((object.ReferenceEquals(this.WindowsServiceExeField, value) != true))
				{
					this.WindowsServiceExeField = value;
					this.RaisePropertyChanged("WindowsServiceExe");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "response", Namespace = "http://schemas.datacontract.org/2004/07/ISI.Libraries.Contracts.DataTransferObjec" +
			"ts")]
	[System.SerializableAttribute()]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployArtifactResponse))]
	public partial class response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "GetStatusResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class GetStatusResponse : ISI.Extensions.Scm.ServiceReferences.ServicesManager.response
	{

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool ActiveField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string CaptionField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntryCollection LogField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private int PercentField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool SuccessField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Active
		{
			get
			{
				return this.ActiveField;
			}
			set
			{
				if ((this.ActiveField.Equals(value) != true))
				{
					this.ActiveField = value;
					this.RaisePropertyChanged("Active");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Caption
		{
			get
			{
				return this.CaptionField;
			}
			set
			{
				if ((object.ReferenceEquals(this.CaptionField, value) != true))
				{
					this.CaptionField = value;
					this.RaisePropertyChanged("Caption");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntryCollection Log
		{
			get
			{
				return this.LogField;
			}
			set
			{
				if ((object.ReferenceEquals(this.LogField, value) != true))
				{
					this.LogField = value;
					this.RaisePropertyChanged("Log");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public int Percent
		{
			get
			{
				return this.PercentField;
			}
			set
			{
				if ((this.PercentField.Equals(value) != true))
				{
					this.PercentField = value;
					this.RaisePropertyChanged("Percent");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool Success
		{
			get
			{
				return this.SuccessField;
			}
			set
			{
				if ((this.SuccessField.Equals(value) != true))
				{
					this.SuccessField = value;
					this.RaisePropertyChanged("Success");
				}
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "UpdateResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class UpdateResponse : ISI.Extensions.Scm.ServiceReferences.ServicesManager.response
	{

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string CurrentVersionField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string LogField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string NewVersionField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private bool SameVersionField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string CurrentVersion
		{
			get
			{
				return this.CurrentVersionField;
			}
			set
			{
				if ((object.ReferenceEquals(this.CurrentVersionField, value) != true))
				{
					this.CurrentVersionField = value;
					this.RaisePropertyChanged("CurrentVersion");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Log
		{
			get
			{
				return this.LogField;
			}
			set
			{
				if ((object.ReferenceEquals(this.LogField, value) != true))
				{
					this.LogField = value;
					this.RaisePropertyChanged("Log");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string NewVersion
		{
			get
			{
				return this.NewVersionField;
			}
			set
			{
				if ((object.ReferenceEquals(this.NewVersionField, value) != true))
				{
					this.NewVersionField = value;
					this.RaisePropertyChanged("NewVersion");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public bool SameVersion
		{
			get
			{
				return this.SameVersionField;
			}
			set
			{
				if ((this.SameVersionField.Equals(value) != true))
				{
					this.SameVersionField = value;
					this.RaisePropertyChanged("SameVersion");
				}
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "DeployArtifactResponse", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployConsoleApplication))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFile))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWebSite))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWindowsService))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployConsoleApplicationResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWebSiteResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWindowsServiceResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentCollection))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentResponseCollection))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntryCollection))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntry))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.response))]
	public partial class DeployArtifactResponse : ISI.Extensions.Scm.ServiceReferences.ServicesManager.response
	{

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentResponseCollection DeployComponentResponsesField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string StatusTrackerKeyField;

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentResponseCollection DeployComponentResponses
		{
			get
			{
				return this.DeployComponentResponsesField;
			}
			set
			{
				if ((object.ReferenceEquals(this.DeployComponentResponsesField, value) != true))
				{
					this.DeployComponentResponsesField = value;
					this.RaisePropertyChanged("DeployComponentResponses");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string StatusTrackerKey
		{
			get
			{
				return this.StatusTrackerKeyField;
			}
			set
			{
				if ((object.ReferenceEquals(this.StatusTrackerKeyField, value) != true))
				{
					this.StatusTrackerKeyField = value;
					this.RaisePropertyChanged("StatusTrackerKey");
				}
			}
		}
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.CollectionDataContractAttribute(Name = "DeployComponentResponseCollection", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects", ItemName = "anyType")]
	[System.SerializableAttribute()]
	public class DeployComponentResponseCollection : System.Collections.Generic.List<object>
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.CollectionDataContractAttribute(Name = "LogEntryCollection", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects", ItemName = "LogEntry")]
	[System.SerializableAttribute()]
	public class LogEntryCollection : System.Collections.Generic.List<ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntry>
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "LogEntry", Namespace = "http://services-manager.isi-net.com/manager/data-transfer-objects")]
	[System.SerializableAttribute()]
	public partial class LogEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private System.DateTime DateTimeStampField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string DescriptionField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public System.DateTime DateTimeStamp
		{
			get
			{
				return this.DateTimeStampField;
			}
			set
			{
				if ((this.DateTimeStampField.Equals(value) != true))
				{
					this.DateTimeStampField = value;
					this.RaisePropertyChanged("DateTimeStamp");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
		public string Description
		{
			get
			{
				return this.DescriptionField;
			}
			set
			{
				if ((object.ReferenceEquals(this.DescriptionField, value) != true))
				{
					this.DescriptionField = value;
					this.RaisePropertyChanged("Description");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://services-manager.isi-net.com", ConfigurationName = "ServiceReferences.ServicesManager.Manager")]
	public interface Manager
	{

		[System.ServiceModel.OperationContractAttribute(Action = "http://services-manager.isi-net.com/Manager/DeployArtifact", ReplyAction = "http://services-manager.isi-net.com/Manager/DeployArtifactResponse")]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployConsoleApplication))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFileCollection))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentExcludeFile))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWebSite))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWindowsService))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployConsoleApplicationResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWebSiteResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployWindowsServiceResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentCollection))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployArtifactResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentResponseCollection))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntryCollection))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.LogEntry))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse))]
		[System.ServiceModel.ServiceKnownTypeAttribute(typeof(ISI.Extensions.Scm.ServiceReferences.ServicesManager.response))]
		ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployArtifactResponse DeployArtifact(string password, string remoteManagementUrl, string authenticationToken, string artifactName, string artifactDateTimeStampVersionUrl, string artifactDownloadUrl, string toDateTimeStamp, string fromEnvironment, string toEnvironment, string configurationKey, ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentCollection deployComponents, bool setDeployedVersion, bool runAsync);

		[System.ServiceModel.OperationContractAttribute(Action = "http://services-manager.isi-net.com/Manager/GetStatus", ReplyAction = "http://services-manager.isi-net.com/Manager/GetStatusResponse")]
		ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse GetStatus(string password, string statusTrackerKey);

		[System.ServiceModel.OperationContractAttribute(Action = "http://services-manager.isi-net.com/Manager/Update", ReplyAction = "http://services-manager.isi-net.com/Manager/UpdateResponse")]
		ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse Update(string password);
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public interface ManagerChannel : ISI.Extensions.Scm.ServiceReferences.ServicesManager.Manager, System.ServiceModel.IClientChannel
	{
	}

	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	public partial class ManagerClient : System.ServiceModel.ClientBase<ISI.Extensions.Scm.ServiceReferences.ServicesManager.Manager>, ISI.Extensions.Scm.ServiceReferences.ServicesManager.Manager
	{

		public ManagerClient()
		{
		}

		public ManagerClient(string endpointConfigurationName) :
						base(endpointConfigurationName)
		{
		}

		public ManagerClient(string endpointConfigurationName, string remoteAddress) :
						base(endpointConfigurationName, remoteAddress)
		{
		}

		public ManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
						base(endpointConfigurationName, remoteAddress)
		{
		}

		public ManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
						base(binding, remoteAddress)
		{
		}

		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployArtifactResponse DeployArtifact(string password, string remoteManagementUrl, string authenticationToken, string artifactName, string artifactDateTimeStampVersionUrl, string artifactDownloadUrl, string toDateTimeStamp, string fromEnvironment, string toEnvironment, string configurationKey, ISI.Extensions.Scm.ServiceReferences.ServicesManager.DeployComponentCollection deployComponents, bool setDeployedVersion, bool runAsync)
		{
			return base.Channel.DeployArtifact(password, remoteManagementUrl, authenticationToken, artifactName, artifactDateTimeStampVersionUrl, artifactDownloadUrl, toDateTimeStamp, fromEnvironment, toEnvironment, configurationKey, deployComponents, setDeployedVersion, runAsync);
		}

		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.GetStatusResponse GetStatus(string password, string statusTrackerKey)
		{
			return base.Channel.GetStatus(password, statusTrackerKey);
		}

		public ISI.Extensions.Scm.ServiceReferences.ServicesManager.UpdateResponse Update(string password)
		{
			return base.Channel.Update(password);
		}
	}
}
