// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable CS8981

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;


#region ISI.Extensions.Ant.T4Embedded
namespace ISI.Extensions.Ant
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Embedded
	{
		public static string _root()
		{
			return "pack://application:,,,/ISI.Extensions.Ant;component/";
		}
	
	}
}
#endregion

#region ISI.Extensions.Ant.T4Resources
namespace ISI.Extensions.Ant
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Resources
	{
		public static string _root()
		{
			return "ISI.Extensions.Ant.";
		}
	
	}
}
#endregion


