// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

#region ISI.Extensions.T4Resources
namespace ISI.Extensions
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Resources
	{
		public static string _root()
		{
			return "ISI.Extensions.";
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Artwork
		{
			public static string _root()
			{
				return string.Format("{0}Artwork.", T4Resources._root());
			}
		
			public static readonly string Lantern_ico = _root() + "Lantern.ico";
			public static System.IO.Stream GetLantern_icoStream()
			{
				return typeof(ISI.Extensions.T4Resources).Assembly.GetManifestResourceStream(Lantern_ico);
			}
			public static readonly string Lantern_png = _root() + "Lantern.png";
			public static System.IO.Stream GetLantern_pngStream()
			{
				return typeof(ISI.Extensions.T4Resources).Assembly.GetManifestResourceStream(Lantern_png);
			}
		}
	}
}
#endregion



