// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

#region ISI.Platforms.ServiceApplication.Services.Test.T4Files
namespace ISI.Platforms.ServiceApplication.Services.Test
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Files
	{
		public static string __root = null;
		public static string _root()
		{
			return (__root ??= ISI.Extensions.VirtualFileVolumesFileProvider.GetPathPrefix(typeof(T4Files)));
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Views
		{
			public static string _root()
			{
				return string.Format("{0}Views/", T4Files._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class _Shared
			{
				public static string _root()
				{
					return string.Format("{0}_Shared/", T4Files.Views._root());
				}
			
				public static readonly string _Layout_cshtml = _root() + "_Layout.cshtml";
			}
			public static readonly string _Layout_cshtml = _root() + "_Layout.cshtml";
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class TestV2
			{
				public static string _root()
				{
					return string.Format("{0}TestV2/", T4Files.Views._root());
				}
			
				public static readonly string _Layout_cshtml = _root() + "_Layout.cshtml";
				public static readonly string Index_cshtml = _root() + "Index.cshtml";
			}
			public static readonly string Index_cshtml = _root() + "Index.cshtml";
			public static readonly string _ViewImports_cshtml = _root() + "_ViewImports.cshtml";
		}
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class wwwroot
		{
			public static string _root()
			{
				return string.Format("{0}wwwroot/", T4Files._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class JavaScripts
			{
				public static string _root()
				{
					return string.Format("{0}JavaScripts/", T4Files.wwwroot._root());
				}
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Files.wwwroot.JavaScripts._root());
					}
				
					public static readonly string _Layout_js = _root() + "_Layout.js";
				}
				public static readonly string _Layout_js = _root() + "_Layout.js";
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class TestV2
				{
					public static string _root()
					{
						return string.Format("{0}TestV2/", T4Files.wwwroot.JavaScripts._root());
					}
				
					public static readonly string _Layout_js = _root() + "_Layout.js";
					public static readonly string Index_js = _root() + "Index.js";
				}
				public static readonly string Index_js = _root() + "Index.js";
			}
			public static readonly string _Shared = _root() + "_Shared";
			public static readonly string TestV2 = _root() + "TestV2";
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class StyleSheets
			{
				public static string _root()
				{
					return string.Format("{0}StyleSheets/", T4Files.wwwroot._root());
				}
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Files.wwwroot.StyleSheets._root());
					}
				
					public static readonly string _Layout_css = _root() + "_Layout.css";
				}
				public static readonly string _Layout_css = _root() + "_Layout.css";
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class TestV2
				{
					public static string _root()
					{
						return string.Format("{0}TestV2/", T4Files.wwwroot.StyleSheets._root());
					}
				
					public static readonly string _Layout_css = _root() + "_Layout.css";
					public static readonly string Index_css = _root() + "Index.css";
				}
				public static readonly string Index_css = _root() + "Index.css";
			}
		}
	}
}
#endregion

#region ISI.Platforms.ServiceApplication.Services.Test.T4Links
namespace ISI.Platforms.ServiceApplication.Services.Test
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Links
	{
		private static Func<string, bool, global::ISI.Extensions.AspNetCore.IContentUrl> _getContentUrl = null;
		public static Func<string, bool, global::ISI.Extensions.AspNetCore.IContentUrl> GetContentUrl 
		{
			get => _getContentUrl ??= (url, isOriginalUrl) => new global::ISI.Extensions.AspNetCore.ContentUrl(url, isOriginalUrl);
			set => _getContentUrl = value;
		}
	
		[ISI.Extensions.AspNetCore.ContentUrlGeneratorSetter]
		public class ContentUrlGeneratorSetter : global::ISI.Extensions.AspNetCore.IContentUrlGeneratorSetter
		{
			public void SetContentUrlGenerator(Func<string, bool, global::ISI.Extensions.AspNetCore.IContentUrl> setter)
			{
				GetContentUrl = setter;
			}
		}
	
		public static string __root = null;
		public static string _root()
		{
			return (__root ??= ISI.Extensions.VirtualFileVolumesFileProvider.GetPathPrefix(typeof(T4Links)));
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class wwwroot
		{
			public static string _root()
			{
				return T4Links._root();
			}
		
			private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
			public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links._root() + "wwwroot", true);
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class JavaScripts
			{
				public static string _root()
				{
					return string.Format("{0}JavaScripts/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "JavaScripts", true);
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Links.wwwroot.JavaScripts._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.JavaScripts._root() + "_Shared", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_js => __Layout_js ??= GetContentUrl(_root() + "_Layout.js", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class TestV2
				{
					public static string _root()
					{
						return string.Format("{0}TestV2/", T4Links.wwwroot.JavaScripts._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.JavaScripts._root() + "TestV2", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_js => __Layout_js ??= GetContentUrl(_root() + "_Layout.js", true);
					private static global::ISI.Extensions.AspNetCore.IContentUrl _Index_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl Index_js => _Index_js ??= GetContentUrl(_root() + "Index.js", true);
				}
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class StyleSheets
			{
				public static string _root()
				{
					return string.Format("{0}StyleSheets/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "StyleSheets", true);
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Links.wwwroot.StyleSheets._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.StyleSheets._root() + "_Shared", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_css = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_css => __Layout_css ??= GetContentUrl(_root() + "_Layout.css", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class TestV2
				{
					public static string _root()
					{
						return string.Format("{0}TestV2/", T4Links.wwwroot.StyleSheets._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.StyleSheets._root() + "TestV2", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_css = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_css => __Layout_css ??= GetContentUrl(_root() + "_Layout.css", true);
					private static global::ISI.Extensions.AspNetCore.IContentUrl _Index_css = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl Index_css => _Index_css ??= GetContentUrl(_root() + "Index.css", true);
				}
			}
		}
	}
}
#endregion

