// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

#region ISI.Extensions.Tests.T4Files
namespace ISI.Extensions.Tests
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Files
	{
		public static string __root = null;
		public static string _root()
		{
			return (__root ??= ISI.Extensions.VirtualFileVolumesFileProvider.GetPathPrefix(typeof(T4Files)));
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class EmailMessageTemplates
		{
			public static string _root()
			{
				return string.Format("{0}EmailMessageTemplates/", T4Files._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class TestEmail
			{
				public static string _root()
				{
					return string.Format("{0}TestEmail/", T4Files.EmailMessageTemplates._root());
				}
			
				public static readonly string _MhtmlLayout_cshtml = _root() + "_MhtmlLayout.cshtml";
				public static readonly string _MhtmlLayout_es_cshtml = _root() + "_MhtmlLayout-es.cshtml";
				public static readonly string Mhtml_cshtml = _root() + "Mhtml.cshtml";
				public static readonly string MhtmlInclude_cshtml = _root() + "MhtmlInclude.cshtml";
				public static readonly string PlainText_cshtml = _root() + "PlainText.cshtml";
			}
		}
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class EmbeddedFileProvider
		{
			public static string _root()
			{
				return string.Format("{0}EmbeddedFileProvider/", T4Files._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class Documents
			{
				public static string _root()
				{
					return string.Format("{0}Documents/", T4Files.EmbeddedFileProvider._root());
				}
			
				public static readonly string TextFile1_txt = _root() + "TextFile1.txt";
			}
		}
	}
}
#endregion


#region ISI.Extensions.Tests.T4Embedded
namespace ISI.Extensions.Tests
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Embedded
	{
		public static string _root()
		{
			return "pack://application:,,,/ISI.Extensions.Tests;component/";
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class EmailMessageTemplates
		{
			public static string _root()
			{
				return string.Format("{0}EmailMessageTemplates/", T4Embedded._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class TestEmail
			{
				public static string _root()
				{
					return string.Format("{0}TestEmail/", T4Embedded.EmailMessageTemplates._root());
				}
			
				public static readonly string _MhtmlLayout_cshtml = _root() + "_MhtmlLayout.cshtml";
				public static readonly string _MhtmlLayout_es_cshtml = _root() + "_MhtmlLayout-es.cshtml";
				public static readonly string Mhtml_cshtml = _root() + "Mhtml.cshtml";
				public static readonly string MhtmlInclude_cshtml = _root() + "MhtmlInclude.cshtml";
				public static readonly string PlainText_cshtml = _root() + "PlainText.cshtml";
			}
		}
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class EmbeddedFileProvider
		{
			public static string _root()
			{
				return string.Format("{0}EmbeddedFileProvider/", T4Embedded._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class Documents
			{
				public static string _root()
				{
					return string.Format("{0}Documents/", T4Embedded.EmbeddedFileProvider._root());
				}
			
				public static readonly string TextFile1_txt = _root() + "TextFile1.txt";
			}
		}
	}
}
#endregion


