#region Copyright & License
/*
Copyright (c) 2023, Integrated Solutions, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

		* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
		* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
		* Neither the name of the Integrated Solutions, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#endregion
 

// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

#region ISI.Extensions.AspNetCore.Tests.T4Files
namespace ISI.Extensions.AspNetCore.Tests
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Files
	{
		public static string __root = "~/";
		public static string _root()
		{
			return (__root ??= ISI.Extensions.VirtualFileVolumesFileProvider.GetPathPrefix(typeof(T4Files)));
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class wwwroot
		{
			public static string _root()
			{
				return string.Format("{0}wwwroot/", T4Files._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class css
			{
				public static string _root()
				{
					return string.Format("{0}css/", T4Files.wwwroot._root());
				}
			
				public static readonly string site_css = _root() + "site.css";
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class JavaScripts
			{
				public static string _root()
				{
					return string.Format("{0}JavaScripts/", T4Files.wwwroot._root());
				}
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Files.wwwroot.JavaScripts._root());
					}
				
					public static readonly string _Layout_js = _root() + "_Layout.js";
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class Public
				{
					public static string _root()
					{
						return string.Format("{0}Public/", T4Files.wwwroot.JavaScripts._root());
					}
				
					public static readonly string _Layout_js = _root() + "_Layout.js";
					public static readonly string Index_js = _root() + "Index.js";
				}
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class js
			{
				public static string _root()
				{
					return string.Format("{0}js/", T4Files.wwwroot._root());
				}
			
				public static readonly string site_js = _root() + "site.js";
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class lib
			{
				public static string _root()
				{
					return string.Format("{0}lib/", T4Files.wwwroot._root());
				}
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class bootstrap
				{
					public static string _root()
					{
						return string.Format("{0}bootstrap/", T4Files.wwwroot.lib._root());
					}
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Files.wwwroot.lib.bootstrap._root());
						}
					
						[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
						public static partial class css
						{
							public static string _root()
							{
								return string.Format("{0}css/", T4Files.wwwroot.lib.bootstrap.dist._root());
							}
						
							public static readonly string bootstrap_css = _root() + "bootstrap.css";
							public static readonly string bootstrap_grid_css = _root() + "bootstrap-grid.css";
							public static readonly string bootstrap_reboot_css = _root() + "bootstrap-reboot.css";
							public static readonly string bootstrap_utilities_css = _root() + "bootstrap-utilities.css";
						}
						[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
						public static partial class js
						{
							public static string _root()
							{
								return string.Format("{0}js/", T4Files.wwwroot.lib.bootstrap.dist._root());
							}
						
							public static readonly string bootstrap_js = _root() + "bootstrap.js";
						}
					}
					public static readonly string LICENSE = _root() + "LICENSE";
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery
				{
					public static string _root()
					{
						return string.Format("{0}jquery/", T4Files.wwwroot.lib._root());
					}
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Files.wwwroot.lib.jquery._root());
						}
					
						public static readonly string jquery_js = _root() + "jquery.js";
					}
					public static readonly string LICENSE_txt = _root() + "LICENSE.txt";
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery_validation
				{
					public static string _root()
					{
						return string.Format("{0}jquery-validation/", T4Files.wwwroot.lib._root());
					}
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Files.wwwroot.lib.jquery_validation._root());
						}
					
						public static readonly string additional_methods_js = _root() + "additional-methods.js";
						public static readonly string jquery_validate_js = _root() + "jquery.validate.js";
					}
					public static readonly string LICENSE_md = _root() + "LICENSE.md";
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery_validation_unobtrusive
				{
					public static string _root()
					{
						return string.Format("{0}jquery-validation-unobtrusive/", T4Files.wwwroot.lib._root());
					}
				
					public static readonly string jquery_validate_unobtrusive_js = _root() + "jquery.validate.unobtrusive.js";
					public static readonly string LICENSE_txt = _root() + "LICENSE.txt";
				}
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class StyleSheets
			{
				public static string _root()
				{
					return string.Format("{0}StyleSheets/", T4Files.wwwroot._root());
				}
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Files.wwwroot.StyleSheets._root());
					}
				
					public static readonly string _Layout_css = _root() + "_Layout.css";
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class Public
				{
					public static string _root()
					{
						return string.Format("{0}Public/", T4Files.wwwroot.StyleSheets._root());
					}
				
					public static readonly string _Layout_css = _root() + "_Layout.css";
					public static readonly string Index_css = _root() + "Index.css";
				}
			}
			public static readonly string favicon_ico = _root() + "favicon.ico";
		}
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Views
		{
			public static string _root()
			{
				return string.Format("{0}Views/", T4Files._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class _Shared
			{
				public static string _root()
				{
					return string.Format("{0}_Shared/", T4Files.Views._root());
				}
			
				public static readonly string _Layout_cshtml = _root() + "_Layout.cshtml";
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class Public
			{
				public static string _root()
				{
					return string.Format("{0}Public/", T4Files.Views._root());
				}
			
				public static readonly string _Layout_cshtml = _root() + "_Layout.cshtml";
				public static readonly string Index_cshtml = _root() + "Index.cshtml";
			}
		}
	}
}
#endregion

#region ISI.Extensions.AspNetCore.Tests.T4Links
namespace ISI.Extensions.AspNetCore.Tests
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Links
	{
		private static Func<string, bool, global::ISI.Extensions.AspNetCore.IContentUrl> _getContentUrl = null;
		public static Func<string, bool, global::ISI.Extensions.AspNetCore.IContentUrl> GetContentUrl 
		{
			get => _getContentUrl ??= (url, isOriginalUrl) => new global::ISI.Extensions.AspNetCore.ContentUrl(url, isOriginalUrl);
			set => _getContentUrl = value;
		}
	
		[ISI.Extensions.AspNetCore.ContentUrlGeneratorSetter]
		public class ContentUrlGeneratorSetter : global::ISI.Extensions.AspNetCore.IContentUrlGeneratorSetter
		{
			public void SetContentUrlGenerator(Func<string, bool, global::ISI.Extensions.AspNetCore.IContentUrl> setter)
			{
				GetContentUrl = setter;
			}
		}
	
		public static string __root = "~/";
		public static string _root()
		{
			return (__root ??= ISI.Extensions.VirtualFileVolumesFileProvider.GetPathPrefix(typeof(T4Links)));
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class wwwroot
		{
			public static string _root()
			{
				return T4Links._root();
			}
		
			private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
			public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links._root() + "wwwroot", true);
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class css
			{
				public static string _root()
				{
					return string.Format("{0}css/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "css", true);
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _site_css = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl site_css => _site_css ??= GetContentUrl(_root() + "site.css", true);
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class JavaScripts
			{
				public static string _root()
				{
					return string.Format("{0}JavaScripts/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "JavaScripts", true);
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Links.wwwroot.JavaScripts._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.JavaScripts._root() + "_Shared", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_js => __Layout_js ??= GetContentUrl(_root() + "_Layout.js", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class Public
				{
					public static string _root()
					{
						return string.Format("{0}Public/", T4Links.wwwroot.JavaScripts._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.JavaScripts._root() + "Public", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_js => __Layout_js ??= GetContentUrl(_root() + "_Layout.js", true);
					private static global::ISI.Extensions.AspNetCore.IContentUrl _Index_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl Index_js => _Index_js ??= GetContentUrl(_root() + "Index.js", true);
				}
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class js
			{
				public static string _root()
				{
					return string.Format("{0}js/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "js", true);
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _site_js = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl site_js => _site_js ??= GetContentUrl(_root() + "site.js", true);
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class lib
			{
				public static string _root()
				{
					return string.Format("{0}lib/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "lib", true);
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class bootstrap
				{
					public static string _root()
					{
						return string.Format("{0}bootstrap/", T4Links.wwwroot.lib._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib._root() + "bootstrap", true);
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Links.wwwroot.lib.bootstrap._root());
						}
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.bootstrap._root() + "dist", true);
					
						[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
						public static partial class css
						{
							public static string _root()
							{
								return string.Format("{0}css/", T4Links.wwwroot.lib.bootstrap.dist._root());
							}
						
							private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.bootstrap.dist._root() + "css", true);
						
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_css => _bootstrap_css ??= GetContentUrl(_root() + "bootstrap.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_grid_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_grid_css => _bootstrap_grid_css ??= GetContentUrl(_root() + "bootstrap-grid.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_reboot_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_reboot_css => _bootstrap_reboot_css ??= GetContentUrl(_root() + "bootstrap-reboot.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_utilities_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_utilities_css => _bootstrap_utilities_css ??= GetContentUrl(_root() + "bootstrap-utilities.css", true);
						}
						[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
						public static partial class js
						{
							public static string _root()
							{
								return string.Format("{0}js/", T4Links.wwwroot.lib.bootstrap.dist._root());
							}
						
							private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.bootstrap.dist._root() + "js", true);
						
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_js = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_js => _bootstrap_js ??= GetContentUrl(_root() + "bootstrap.js", true);
						}
					}
					private static global::ISI.Extensions.AspNetCore.IContentUrl _LICENSE = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl LICENSE => _LICENSE ??= GetContentUrl(_root() + "LICENSE", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery
				{
					public static string _root()
					{
						return string.Format("{0}jquery/", T4Links.wwwroot.lib._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib._root() + "jquery", true);
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Links.wwwroot.lib.jquery._root());
						}
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.jquery._root() + "dist", true);
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _jquery_js = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl jquery_js => _jquery_js ??= GetContentUrl(_root() + "jquery.js", true);
					}
					private static global::ISI.Extensions.AspNetCore.IContentUrl _LICENSE_txt = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl LICENSE_txt => _LICENSE_txt ??= GetContentUrl(_root() + "LICENSE.txt", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery_validation
				{
					public static string _root()
					{
						return string.Format("{0}jquery-validation/", T4Links.wwwroot.lib._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib._root() + "jquery-validation", true);
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Links.wwwroot.lib.jquery_validation._root());
						}
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.jquery_validation._root() + "dist", true);
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _additional_methods_js = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl additional_methods_js => _additional_methods_js ??= GetContentUrl(_root() + "additional-methods.js", true);
						private static global::ISI.Extensions.AspNetCore.IContentUrl _jquery_validate_js = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl jquery_validate_js => _jquery_validate_js ??= GetContentUrl(_root() + "jquery.validate.js", true);
					}
					private static global::ISI.Extensions.AspNetCore.IContentUrl _LICENSE_md = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl LICENSE_md => _LICENSE_md ??= GetContentUrl(_root() + "LICENSE.md", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery_validation_unobtrusive
				{
					public static string _root()
					{
						return string.Format("{0}jquery-validation-unobtrusive/", T4Links.wwwroot.lib._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib._root() + "jquery-validation-unobtrusive", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _jquery_validate_unobtrusive_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl jquery_validate_unobtrusive_js => _jquery_validate_unobtrusive_js ??= GetContentUrl(_root() + "jquery.validate.unobtrusive.js", true);
					private static global::ISI.Extensions.AspNetCore.IContentUrl _LICENSE_txt = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl LICENSE_txt => _LICENSE_txt ??= GetContentUrl(_root() + "LICENSE.txt", true);
				}
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class StyleSheets
			{
				public static string _root()
				{
					return string.Format("{0}StyleSheets/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "StyleSheets", true);
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Links.wwwroot.StyleSheets._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.StyleSheets._root() + "_Shared", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_css = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_css => __Layout_css ??= GetContentUrl(_root() + "_Layout.css", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class Public
				{
					public static string _root()
					{
						return string.Format("{0}Public/", T4Links.wwwroot.StyleSheets._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.StyleSheets._root() + "Public", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_css = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_css => __Layout_css ??= GetContentUrl(_root() + "_Layout.css", true);
					private static global::ISI.Extensions.AspNetCore.IContentUrl _Index_css = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl Index_css => _Index_css ??= GetContentUrl(_root() + "Index.css", true);
				}
			}
			private static global::ISI.Extensions.AspNetCore.IContentUrl _favicon_ico = null;
			public static global::ISI.Extensions.AspNetCore.IContentUrl favicon_ico => _favicon_ico ??= GetContentUrl(_root() + "favicon.ico", true);
		}
	}
}
#endregion

